### ISSUE TITLE
Memory error?!

### ISSUE THREAD

**Issue by satroan** [llSourcell/wiki_generator_live#1]
that is a new one for me any help? Love your videos...Has my comp become too puny to host the Great Siraj's AI now :p

 ```
python democodewiki.py 
('text length in number of characters:', 1290590)
head of text:
 
 = Robert Boulter = 
 
 Robert Boulter is an English film , television and theatre actor . He had a guest @-@ starring role on the television series The Bill in 2000 . This was followed by a starring role in the play Herons written by Simon Stephens , which was performed in 2001 at the Royal Court Theatre . He had a guest role in the television series Judge John Deed in 2002 . In 2004 Boulter landed a role as " Craig " in the episode " Teddy 's Story " of the television series The Long Firm ; he starred alongside actors Mark Strong and Derek Jacobi . He was cast in the 2005 theatre productions of the Philip Ridley play Mercury Fur , which was performed at the Drum Theatre in Plymouth and the Menier Chocolate Factory in London . He was directed by John Tiffany and starred alongside Ben Whishaw , Shane Zaza , Harry Kent , Fraser Ayres , Sophie Stanton and Dominic Hall . 
 In 2006 , Boulter starred alongside Whishaw in the play Citizenship written by Mark Ravenhill . He appeared on a 20
('number of characters:', 178)
['\n', ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '^', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\x80', '\x81', '\x82', '\x83', '\x84', '\x85', '\x86', '\x87', '\x88', '\x89', '\x8a', '\x8b', '\x8c', '\x8d', '\x8e', '\x8f', '\x90', '\x91', '\x92', '\x93', '\x94', '\x95', '\x96', '\x97', '\x98', '\x99', '\x9b', '\x9c', '\x9d', '\x9e', '\x9f', '\xa0', '\xa1', '\xa2', '\xa3', '\xa4', '\xa5', '\xa6', '\xa7', '\xa8', '\xa9', '\xaa', '\xab', '\xad', '\xae', '\xaf', '\xb0', '\xb1', '\xb2', '\xb3', '\xb4', '\xb5', '\xb6', '\xb7', '\xb8', '\xb9', '\xba', '\xbb', '\xbc', '\xbd', '\xbe', '\xbf', '\xc2', '\xc3', '\xc4', '\xc5', '\xc7', '\xc9', '\xca', '\xcb', '\xcc', '\xcd', '\xce', '\xcf', '\xd0', '\xd7', '\xd8', '\xd9', '\xda', '\xe0', '\xe1', '\xe2', '\xe3', '\xe4', '\xe5', '\xe6', '\xe7', '\xe8', '\xe9']
hello
Traceback (most recent call last):
  File "democodewiki.py", line 100, in <module>
    X = np.zeros((len(sections), len_per_section, char_size))
MemoryError

```

**Comment by psychomonkey911** [comment]
i have error 

```
#vectorize our data to feed it into model

len_per_section = 50
skip = 2
sections = []
next_chars = []
#fill sections list with chunks of text, every 2 characters create a new 50 
#character long section
#because we are generating it at a character level
for i in range(0, len(text) - len_per_section, skip):
    sections.append(text[i: i + len_per_section])
    next_chars.append(text[i + len_per_section])
#Vectorize input and output
#matrix of section length by num of characters
X = np.zeros((len(sections), len_per_section, char_size))
#label column for all the character id's, still zero
y = np.zeros((len(sections), char_size))
#for each char in each section, convert each char to an ID
#for each section convert the labels to ids 
for i, section in enumerate(sections):
    for j, char in enumerate(section):
        X[i, j, char2id[char]] = 1
    y[i, char2id[next_chars[i]]] = 1
print(y)
```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-7-6a70656de7c4> in <module>()
     13 #Vectorize input and output
     14 #matrix of section length by num of characters
---> 15 X = np.zeros((len(sections), len_per_section, char_size))
     16 #label column for all the character id's, still zero
     17 y = np.zeros((len(sections), char_size))

MemoryError: 



help me plz

**Comment by matbest** [comment]
I too had this problem, I've just cut my text block down to 10000 chars, probably won't be able to train with just that, but at least it runs...

I'm running on windows 10 on a laptop, python 3.5 in anaconda. 

I can confirm that I'm using 64 bit though with:
In [18]:
import platform
platform.architecture()
Out[18]:
('64bit', 'WindowsPE')

**Comment by expenses** [comment]
I'm on an Arch system with 24gb of mem and I still get an error at:

`X = np.zeros((len(sections), len_per_section, char_size))`

Running `print(len(sections), len_per_section, char_size)` gives me `639642 50 157`. Don't know why the length of the sections is so high - no wonder you run out of memory trying to allocate 5021189700 floats!

**Comment by psychomonkey911** [comment]
print(len(sections), len_per_section, char_size)
(299851, 50, 157)

---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-14-c4e6f0a7b4b9> in <module>()
     14 #matrix of section length by num of characters
     15 print(len(sections), len_per_section, char_size)
---> 16 X = np.zeros((len(sections), len_per_section, char_size))
     17 #label column for all the character id's, still zero
     18 y = np.zeros((len(sections), char_size))

MemoryError:

**Comment by expenses** [comment]
I just tested `X = np.zeros( (299851, 50, 157))` on my (much slower) OSX laptop and it works fine. It appears then that this main problem here is how different OSes allocate memory when np.zeros is called (http://stackoverflow.com/questions/27464039/why-the-performance-difference-between-numpy-zeros-and-numpy-zeros-like). Any one know of a solution to this? I.E. How do I get np.zeros to allocate memory on-the-fly in Linux?

**Comment by BenjiKCF** [comment]
Use this to reduce the size of text and it will work fine.
```
text = open('wiki.test.raw', encoding="utf8").read()
text = text[:50000]
```

**Comment by psychomonkey911** [comment]
good day!
I have error, help me fix plz.
```
logs:

2017-05-17 12:04:12,739 INFO - training loss at step 71970: 0.72 (2017-05-17 19:03:51.043188)
2017-05-17 12:04:12,739 INFO - training loss at step 71980: 0.71 (2017-05-17 19:03:57.473567)
2017-05-17 12:04:12,739 INFO - training loss at step 71990: 0.69 (2017-05-17 19:04:04.435141)
2017-05-17 12:04:12,739 INFO - training loss at step 72000: 0.67 (2017-05-17 19:04:10.741502)
2017-05-17 12:04:12,740 INFO - Traceback (most recent call last):
2017-05-17 12:04:12,740 INFO - File "diet.py", line 320, in <module>
2017-05-17 12:04:12,740 INFO - reset_test_state.run()
2017-05-17 12:04:12,741 INFO - NameError: name 'reset_test_state' is not defined
2017-05-17 12:04:13,138 INFO - 
################################################################################
```
**NameError: name 'reset_test_state' is not defined**
**How fix it?**

**Comment by qo4on** [comment]
> Any one know of a solution to this? I.E. How do I get np.zeros to allocate memory on-the-fly in Linux?

Have anyone fixed this?

**Comment by saini-pankaj** [comment]
hey ,just used numpy.zeros_like ,it work like charm in google  collab
