### ISSUE TITLE
After Traceback (most recent call last):

### ISSUE THREAD

**Issue by linuxcodingdeb** [llSourcell/wiki_generator_live#2]
> line 230, in <module>
>     outputs_all_i = tf.concat(0, [outputs_all_i, output])
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1047, in concat
>     dtype=dtypes.int32).get_shape(
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 651, in convert_to_tensor
>     as_ref=False)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
>     ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
>     return constant(v, dtype=dtype, name=name)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
>     tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
>     _AssertCompatible(values, dtype)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
>     (dtype.name, repr(mismatch), type(mismatch).__name__))
> TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by sherlockhoatszx** [comment]
yes, I got the same error here ,how do you solve this

**Comment by sherlockhoatszx** [comment]
oh, I read the api and change the  tf.concat(0, [outputs_all_i, output])to tf.concat([output_all_i,output],0), that  works for me
